package org.egg.model.DO;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.user_no
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.user_head_pic
     *
     * @mbggenerated
     */
    private String userHeadPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.tel_no
     *
     * @mbggenerated
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.wx_open_id
     *
     * @mbggenerated
     */
    private String wxOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.wx_mini_open_id
     *
     * @mbggenerated
     */
    private String wxMiniOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.sch_name
     *
     * @mbggenerated
     */
    private String schName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.address_l
     *
     * @mbggenerated
     */
    private String addressL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.address_q
     *
     * @mbggenerated
     */
    private String addressQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.user_status
     *
     * @mbggenerated
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.real_status
     *
     * @mbggenerated
     */
    private String realStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.real_id_no
     *
     * @mbggenerated
     */
    private String realIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.credit_score
     *
     * @mbggenerated
     */
    private Integer creditScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.balance
     *
     * @mbggenerated
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.modified_date
     *
     * @mbggenerated
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.id
     *
     * @return the value of user_stu.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.id
     *
     * @param id the value for user_stu.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.user_no
     *
     * @return the value of user_stu.user_no
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.user_no
     *
     * @param userNo the value for user_stu.user_no
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.real_name
     *
     * @return the value of user_stu.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.real_name
     *
     * @param realName the value for user_stu.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.gender
     *
     * @return the value of user_stu.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.gender
     *
     * @param gender the value for user_stu.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.nick_name
     *
     * @return the value of user_stu.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.nick_name
     *
     * @param nickName the value for user_stu.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.user_head_pic
     *
     * @return the value of user_stu.user_head_pic
     *
     * @mbggenerated
     */
    public String getUserHeadPic() {
        return userHeadPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.user_head_pic
     *
     * @param userHeadPic the value for user_stu.user_head_pic
     *
     * @mbggenerated
     */
    public void setUserHeadPic(String userHeadPic) {
        this.userHeadPic = userHeadPic == null ? null : userHeadPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.tel_no
     *
     * @return the value of user_stu.tel_no
     *
     * @mbggenerated
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.tel_no
     *
     * @param telNo the value for user_stu.tel_no
     *
     * @mbggenerated
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.password
     *
     * @return the value of user_stu.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.password
     *
     * @param password the value for user_stu.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.wx_open_id
     *
     * @return the value of user_stu.wx_open_id
     *
     * @mbggenerated
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.wx_open_id
     *
     * @param wxOpenId the value for user_stu.wx_open_id
     *
     * @mbggenerated
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.wx_mini_open_id
     *
     * @return the value of user_stu.wx_mini_open_id
     *
     * @mbggenerated
     */
    public String getWxMiniOpenId() {
        return wxMiniOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.wx_mini_open_id
     *
     * @param wxMiniOpenId the value for user_stu.wx_mini_open_id
     *
     * @mbggenerated
     */
    public void setWxMiniOpenId(String wxMiniOpenId) {
        this.wxMiniOpenId = wxMiniOpenId == null ? null : wxMiniOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.sch_name
     *
     * @return the value of user_stu.sch_name
     *
     * @mbggenerated
     */
    public String getSchName() {
        return schName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.sch_name
     *
     * @param schName the value for user_stu.sch_name
     *
     * @mbggenerated
     */
    public void setSchName(String schName) {
        this.schName = schName == null ? null : schName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.address_l
     *
     * @return the value of user_stu.address_l
     *
     * @mbggenerated
     */
    public String getAddressL() {
        return addressL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.address_l
     *
     * @param addressL the value for user_stu.address_l
     *
     * @mbggenerated
     */
    public void setAddressL(String addressL) {
        this.addressL = addressL == null ? null : addressL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.address_q
     *
     * @return the value of user_stu.address_q
     *
     * @mbggenerated
     */
    public String getAddressQ() {
        return addressQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.address_q
     *
     * @param addressQ the value for user_stu.address_q
     *
     * @mbggenerated
     */
    public void setAddressQ(String addressQ) {
        this.addressQ = addressQ == null ? null : addressQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.remark
     *
     * @return the value of user_stu.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.remark
     *
     * @param remark the value for user_stu.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.user_status
     *
     * @return the value of user_stu.user_status
     *
     * @mbggenerated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.user_status
     *
     * @param userStatus the value for user_stu.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.real_status
     *
     * @return the value of user_stu.real_status
     *
     * @mbggenerated
     */
    public String getRealStatus() {
        return realStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.real_status
     *
     * @param realStatus the value for user_stu.real_status
     *
     * @mbggenerated
     */
    public void setRealStatus(String realStatus) {
        this.realStatus = realStatus == null ? null : realStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.real_id_no
     *
     * @return the value of user_stu.real_id_no
     *
     * @mbggenerated
     */
    public String getRealIdNo() {
        return realIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.real_id_no
     *
     * @param realIdNo the value for user_stu.real_id_no
     *
     * @mbggenerated
     */
    public void setRealIdNo(String realIdNo) {
        this.realIdNo = realIdNo == null ? null : realIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.credit_score
     *
     * @return the value of user_stu.credit_score
     *
     * @mbggenerated
     */
    public Integer getCreditScore() {
        return creditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.credit_score
     *
     * @param creditScore the value for user_stu.credit_score
     *
     * @mbggenerated
     */
    public void setCreditScore(Integer creditScore) {
        this.creditScore = creditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.balance
     *
     * @return the value of user_stu.balance
     *
     * @mbggenerated
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.balance
     *
     * @param balance the value for user_stu.balance
     *
     * @mbggenerated
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.version
     *
     * @return the value of user_stu.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.version
     *
     * @param version the value for user_stu.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.created_date
     *
     * @return the value of user_stu.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.created_date
     *
     * @param createdDate the value for user_stu.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stu.modified_date
     *
     * @return the value of user_stu.modified_date
     *
     * @mbggenerated
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stu.modified_date
     *
     * @param modifiedDate the value for user_stu.modified_date
     *
     * @mbggenerated
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}