package org.egg.model.DTO;

import lombok.Data;

/**
 * @author dataochen
 * @Description
 * @date: 2019/12/5 20:59
 */
@Data
public class UserModifyDto {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.gender
     * 值为1时是男性，值为2时是女性，值为0时是未知
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.nick_name
     *
     * @mbggenerated
     */
    private String nickName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.sch_name
     *
     * @mbggenerated
     */
    private String schName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.address_l
     *
     * @mbggenerated
     */
    private String addressL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.address_q
     *
     * @mbggenerated
     */
    private String addressQ;


}
