package org.egg.model.VO;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by chendatao on 2017/12/7.
 */
@Data
public class UserInfoRes implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.user_no
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.user_head_pic
     *
     * @mbggenerated
     */
    private String userHeadPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.tel_no
     *
     * @mbggenerated
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.wx_open_id
     *
     * @mbggenerated
     */
    private String wxOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.wx_mini_open_id
     *
     * @mbggenerated
     */
    private String wxMiniOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.sch_name
     *
     * @mbggenerated
     */
    private String schName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.address_l
     *
     * @mbggenerated
     */
    private String addressL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.address_q
     *
     * @mbggenerated
     */
    private String addressQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.remark
     *
     * @mbggenerated
     */
    private String remark;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.real_status
     *
     * @mbggenerated
     */
    private String realStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.real_id_no
     *
     * @mbggenerated
     */
    private String realIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.credit_score
     *
     * @mbggenerated
     */
    private Integer creditScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.balance
     *
     * @mbggenerated
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stu.modified_date
     *
     * @mbggenerated
     */
    private Date modifiedDate;

}
